repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(build/|infra/.*/\.terraform/|dist/)
      - id: ruff-format
        exclude: ^(build/|infra/.*/\.terraform/|dist/)